apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-postgres
  template:
    metadata:
      labels:
        app: taskflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: taskflow_db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: taskflow-postgres
  ports:
    - port: 5432
      targetPort: 5432
